# Generated by Django 4.2.11 on 2024-07-02 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='group_files/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to='api.group')),
            ],
        ),
    ]
